In [38]:
import numpy as np
from open3d import *
import plotly
#plotly.__version__

In [39]:
print("Load a ply point cloud, print it, and render it")
pcd = read_point_cloud("01.ply")
print(pcd)
#draw_geometries([pcd])


Load a ply point cloud, print it, and render it
PointCloud with 1272877 points.


In [40]:
import pptk
import numpy as np
tmp=np.asarray(pcd.points)
print(tmp[0:5,0:3])#rows and column
v = pptk.viewer(tmp)


[[-0.76991999  0.31530058  1.28320003]
 [-0.76134002  0.32145467  1.26890004]
 [-0.75576001  0.32869563  1.25960004]
 [-0.74207997  0.33216915  1.23679996]
 [-0.73673999  0.33913428  1.22790003]]


In [41]:
print("Downsample the point cloud with a voxel of 0.005")
downpcd = voxel_down_sample(pcd, voxel_size = 1)
#draw_geometries([downpcd])
tmp=np.asarray(pcd.points)
v = pptk.viewer(tmp)


Downsample the point cloud with a voxel of 0.005


In [43]:
print("Load a ply point cloud, print it, and render it")
pcd = read_point_cloud("bun0.pcd")
print(pcd)
tmp=np.asarray(pcd.points)
#print(tmp[0:5,0:3])#rows and column
#draw_geometries([pcd])
v = pptk.viewer(tmp)


Load a ply point cloud, print it, and render it
PointCloud with 397 points.
